nama = input("masukan nama : ")
umur = input("masukan umur : ")
alamat = input("masukan alamat : ")
jurusan = input("masukan jurusan : ")

print("\n----biodata----")
print("nama : " + nama)
print("umur : " + umur)
print("alamat : " + alamat)
print("jurusan : " + jurusan)
